services:
  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:${OP_GETH_VERSION}
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/${NETWORK_NAME}/start-op-geth.sh
    env_file:
      - ./envs/${NETWORK_NAME}/op-geth.env
      - .env
    volumes:
      - ./scripts/:/scripts
      - ./config/:/config
      - /op-data/:/op-data
    ports:
      - 8545:8545
      - 8546:8546
      - 39393:39393/udp
      - 39393:39393/tcp

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:${OP_NODE_VERSION}
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/${NETWORK_NAME}/start-op-node.sh
    env_file:
      - ./envs/${NETWORK_NAME}/op-node.env
      - .env
    volumes:
      - ./scripts/:/scripts
      - ./config/:config
      - /op-data/:/op-data
    ports:
      - 9003:9003/udp
      - 9003:9003/tcp
      - 9545:9545


  geth:
    image: ethereum/client-go:v1.15.2
    container_name: geth
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/${NETWORK_NAME}/start-geth.sh
    env_file:
      - .env
    volumes:
      - ./scripts/:/scripts
      - /data/:/data
    ports:
      - 8547:8545
      - 8548:8546
      - 30303:30303
      - 30303:30303


  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v5.3.0
    container_name: prysm-beacon
    restart: unless-stopped
    stop_grace_period: 5m 
    volumes:
      - /data/:/data
    ports:
      - 4000:4000     
      - 3500:3500     
      - 8080:8080   
    command:
      - "--checkpoint-sync-url=https://your-beacon-url"
      - "--genesis-beacon-api-url=https://your-beacon-url"
      - "--datadir=/data/prysm-data"
      - "--jwt-secret=/data/secret.jwt"
      - "--execution-endpoint=http://geth:8551"
      - "--rpc-host=0.0.0.0"
      - "--grpc-gateway-host=0.0.0.0"
      - "--monitoring-host=0.0.0.0"
      - "--accept-terms-of-use"


  prometheus:
    image: prom/prometheus:v3.1.0
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - /prometheus_data:/prometheus
    ports:
      - 9090:9090


  grafana:
    image: grafana/grafana:11.5.1
    restart: unless-stopped
    env_file:
      - ./config/monitoring/grafana.env
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/:ro
      - ./docker/grafana/dashboards/simple_node_dashboard.json:/var/lib/grafana/dashboards/simple_node_dashboard.json
      - /grafana_data:/var/lib/grafana
    ports:
      - 3000:3000


  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    env_file:
      - ./envs/common/influxdb.env
    volumes:
      - ./docker/influxdb/influx_init.iql:/docker-entrypoint-initdb.d/influx_init.iql
      - /influxdb_data:/var/lib/influxdb
    ports:
      - 8086:8086


volumes:
  data:
  op-data:
  grafana_data:
  prometheus_data:
  influxdb_data:
