services:
  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101500.1
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/${NETWORK_NAME}/start-op-geth.sh
    env_file:
      - .env
    volumes:
      - ./scripts/:/scripts
      - /op-data/:/op-data
    ports:
      - 8545:8545
      - 8546:8546
      - 39393:39393/udp
      - 39393:39393/tcp

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.11.2
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/${NETWORK_NAME}/start-op-node.sh
    env_file:
      - .env
    volumes:
      - ./scripts/:/scripts
      - /op-data/:/op-data
    ports:
      - 9003:9003/udp
      - 9003:9003/tcp
      - 9545:9545


  geth:
    image: ethereum/client-go:v1.15.2
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/${NETWORK_NAME}/start-geth.sh
    env_file:
      - .env
    volumes:
      - ./scripts/:/scripts
      - /data/:/data
    ports:
      - 8547:8545
      - 8548:8546
      - 30303:30303
      - 30303:30303


  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v5.3.0
    container_name: prysm-beacon
    restart: unless-stopped
    ports:
      - 4000:4000     
      - 3500:3500     
      - 8080:8080    
    volumes:
      - /data/:/data
    command:
      - "--checkpoint-sync-url=https://your-beacon-url"
      - "--genesis-beacon-api-url=https://your-beacon-url"
      - "--datadir=/data/prysm-data"
      - "--jwt-secret=/data/secret.jwt"
      - "--execution-endpoint=http://geth:8551"
      - "--rpc-host=0.0.0.0"
      - "--grpc-gateway-host=0.0.0.0"
      - "--monitoring-host=0.0.0.0"
      - "--accept-terms-of-use"

