{
 "title": "Simple Node Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "OP-Geth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OP-Geth Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"op-geth-node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OP-Geth Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "p2p_peers{job=\"op-geth-node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OP-Geth Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "increase(chain_head_block{job=\"op-geth-node\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "OP-Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "OP-Node Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "up{instance=\"op-node:7300\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OP-Node Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "op_node_default_p2p_accepts{instance=\"op-node:7300\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OP-Node Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "op_node_default_up{instance=\"op-node:7300\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Bare Metal Host Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Used CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Disk Storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}) / node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}