global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'op-node'
    static_configs:
    - targets: ['op-node:7300']
  - job_name: "node_exporter"
    static_configs:
      - targets: ["your-vm-ip:9100"]
  - job_name: "op-geth-node"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["op-geth:6060"]
